<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\PlannerController;
use Illuminate\Support\Facades\Route;

Route::get('/{any?}', function () {
    return view('welcome');
})->where('any', '^(?!api).*$');

Route::prefix('api')->group(function () {
    Route::post('/login', [AuthController::class, 'login'])->middleware('guest')->name('login');
    Route::post('/register', [AuthController::class, 'register'])->middleware('guest');
    Route::post('/phone-code', [AuthController::class, 'sendPhoneCode'])->middleware('guest');
    Route::post('/phone-code/verify', [AuthController::class, 'verifyPhoneCode'])->middleware('guest');
    Route::post('/phone-login', [AuthController::class, 'phoneLogin'])->middleware('guest');
    Route::post('/phone-register', [AuthController::class, 'phoneRegister'])->middleware('guest');
    Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth');
    Route::get('/shared-notes/{token}', [PlannerController::class, 'publicNotebookNote']);

    Route::middleware('auth')->group(function () {
        Route::get('/user', [AuthController::class, 'user']);
        Route::post('/profile', [AuthController::class, 'updateProfile']);
        Route::get('/categories', [PlannerController::class, 'categories']);
        Route::post('/categories', [PlannerController::class, 'storeCategory']);
        Route::post('/categories/reorder', [PlannerController::class, 'reorderCategories']);
        Route::put('/categories/{category}', [PlannerController::class, 'updateCategory']);
        Route::delete('/categories/{category}', [PlannerController::class, 'destroyCategory']);
        Route::get('/task-groups', [PlannerController::class, 'taskGroups']);
        Route::post('/task-groups', [PlannerController::class, 'storeTaskGroup']);
        Route::post('/task-groups/reorder', [PlannerController::class, 'reorderTaskGroups']);
        Route::put('/task-groups/{taskGroup}', [PlannerController::class, 'updateTaskGroup']);
        Route::delete('/task-groups/{taskGroup}', [PlannerController::class, 'destroyTaskGroup']);
        Route::get('/group-tasks', [PlannerController::class, 'groupTasks']);
        Route::post('/group-task-projects', [PlannerController::class, 'storeGroupTaskProject']);
        Route::delete('/group-task-projects/{project}', [PlannerController::class, 'destroyGroupTaskProject']);
        Route::post('/group-task-projects/{project}/items', [PlannerController::class, 'storeGroupTaskItem']);
        Route::post('/group-task-projects/{project}/items/reorder', [PlannerController::class, 'reorderGroupTaskItems']);
        Route::put('/group-task-items/{item}', [PlannerController::class, 'updateGroupTaskItem']);
        Route::delete('/group-task-items/{item}', [PlannerController::class, 'destroyGroupTaskItem']);
        Route::get('/priorities', [PlannerController::class, 'priorities']);
        Route::post('/priorities', [PlannerController::class, 'storePriority']);
        Route::put('/priorities/{priority}', [PlannerController::class, 'updatePriority']);
        Route::delete('/priorities/{priority}', [PlannerController::class, 'destroyPriority']);
        Route::get('/daily-planner', [PlannerController::class, 'daily']);
        Route::get('/goals', [PlannerController::class, 'goals']);
        Route::post('/goals', [PlannerController::class, 'storeGoal']);
        Route::get('/goals/{goal}', [PlannerController::class, 'showGoal']);
        Route::post('/goals/{goal}/progress', [PlannerController::class, 'logGoalProgress']);
        Route::put('/goals/{goal}/status', [PlannerController::class, 'updateGoalStatus']);
        Route::post('/goals/{goal}/milestones/{milestone}/toggle', [PlannerController::class, 'toggleGoalMilestone']);
        Route::delete('/goals/{goal}', [PlannerController::class, 'destroyGoal']);
        Route::get('/monthly-report', [PlannerController::class, 'monthlyReport']);
        Route::get('/finance-dashboard', [PlannerController::class, 'financeDashboard']);
        Route::post('/finance-obligations', [PlannerController::class, 'storeFinanceObligation']);
        Route::post('/finance-obligations/{obligation}/pay', [PlannerController::class, 'payFinanceObligation']);
        Route::delete('/finance-obligation-payments/{payment}', [PlannerController::class, 'destroyFinanceObligationPayment']);
        Route::get('/support-tickets', [PlannerController::class, 'supportTickets']);
        Route::post('/support-tickets', [PlannerController::class, 'storeSupportTicket']);
        Route::delete('/support-tickets/{ticket}', [PlannerController::class, 'destroySupportTicket']);
        Route::get('/admin/support-tickets', [PlannerController::class, 'adminSupportTickets']);
        Route::put('/admin/support-tickets/{ticket}/reply', [PlannerController::class, 'replySupportTicket']);
        Route::post('/tasks', [PlannerController::class, 'storeTask']);
        Route::put('/tasks/{task}', [PlannerController::class, 'updateTask']);
        Route::post('/tasks/reorder', [PlannerController::class, 'reorderTasks']);
        Route::post('/tasks/{task}/complete', [PlannerController::class, 'complete']);
        Route::post('/tasks/{task}/refer', [PlannerController::class, 'referTask']);
        Route::delete('/tasks/{task}', [PlannerController::class, 'destroyTask']);
        Route::post('/tasks/{task}/timer/{action}', [PlannerController::class, 'timer'])->whereIn('action', ['start', 'pause', 'resume', 'stop']);
        Route::post('/tasks/{task}/time-sessions', [PlannerController::class, 'storeTimeSession']);
        Route::put('/task-time-sessions/{session}', [PlannerController::class, 'updateTimeSession']);
        Route::delete('/task-time-sessions/{session}', [PlannerController::class, 'destroyTimeSession']);
        Route::post('/follow-ups', [PlannerController::class, 'storeFollowUp']);
        Route::put('/follow-ups/{followUp}', [PlannerController::class, 'updateFollowUp']);
        Route::post('/follow-ups/{followUp}/toggle', [PlannerController::class, 'toggleFollowUp']);
        Route::delete('/follow-ups/{followUp}', [PlannerController::class, 'destroyFollowUp']);
        Route::post('/expenses', [PlannerController::class, 'storeExpense']);
        Route::delete('/expenses/{expense}', [PlannerController::class, 'destroyExpense']);
        Route::get('/expense-categories', [PlannerController::class, 'expenseCategories']);
        Route::post('/expense-categories', [PlannerController::class, 'storeExpenseCategory']);
        Route::post('/expense-categories/reorder', [PlannerController::class, 'reorderExpenseCategories']);
        Route::put('/expense-categories/{expenseCategory}', [PlannerController::class, 'updateExpenseCategory']);
        Route::delete('/expense-categories/{expenseCategory}', [PlannerController::class, 'destroyExpenseCategory']);
        Route::get('/financial-accounts', [PlannerController::class, 'financialAccounts']);
        Route::post('/financial-accounts', [PlannerController::class, 'storeFinancialAccount']);
        Route::post('/financial-accounts/reorder', [PlannerController::class, 'reorderFinancialAccounts']);
        Route::put('/financial-accounts/{account}', [PlannerController::class, 'updateFinancialAccount']);
        Route::delete('/financial-accounts/{account}', [PlannerController::class, 'destroyFinancialAccount']);
        Route::put('/daily-note', [PlannerController::class, 'updateDailyNote']);
        Route::post('/meals', [PlannerController::class, 'storeMeal']);
        Route::put('/meals/{meal}', [PlannerController::class, 'updateMeal']);
        Route::delete('/meals/{meal}', [PlannerController::class, 'destroyMeal']);
        Route::post('/meals/reorder', [PlannerController::class, 'reorderMeals']);
        Route::post('/meals/{meal}/toggle', [PlannerController::class, 'toggleMeal']);
        Route::put('/routine', [PlannerController::class, 'updateRoutine']);
        Route::post('/routine-items', [PlannerController::class, 'storeRoutineItem']);
        Route::put('/routine-items/{routineItem}', [PlannerController::class, 'updateRoutineItem']);
        Route::post('/routine-items/{routineItem}/toggle', [PlannerController::class, 'toggleRoutineItem']);
        Route::delete('/routine-items/{routineItem}', [PlannerController::class, 'destroyRoutineItem']);
        Route::post('/daily-reviews', [PlannerController::class, 'review']);
        Route::get('/notebook-notes', [PlannerController::class, 'notebookNotes']);
        Route::post('/notebook-note-groups', [PlannerController::class, 'storeNotebookNoteGroup']);
        Route::put('/notebook-note-groups/{group}', [PlannerController::class, 'updateNotebookNoteGroup']);
        Route::delete('/notebook-note-groups/{group}', [PlannerController::class, 'destroyNotebookNoteGroup']);
        Route::post('/notebook-notes', [PlannerController::class, 'storeNotebookNote']);
        Route::post('/notebook-notes/images', [PlannerController::class, 'uploadNotebookNoteImage']);
        Route::put('/notebook-notes/{note}', [PlannerController::class, 'updateNotebookNote']);
        Route::post('/notebook-notes/{note}/share', [PlannerController::class, 'shareNotebookNote']);
        Route::delete('/notebook-notes/{note}', [PlannerController::class, 'destroyNotebookNote']);
    });
});
